### PR TITLE
fix(fd2): Added WSL2 Support

### LINKED ISSUE #76: fd2-up.linux.bash does not setup proper groups
## Current Design 
When running the `./fd2-up.bash` command within the bin directory on Windows 10 with WSL2, the following error is outputted by the console: 
image
The VNC still goes up, but you cannot open the terminal 
https://github.com/FarmData2/FarmData2/assets/31524934/3c7564a4-0dc7-48f5-949c-c2de1f2a4a2b

## Desired Design 
There needs to be a fix to the database error and an analysis as to why the vnc isn't working correctly on Windows 10 running WSL2.

### PR DESCRIPTION
**Pull request by JingyuMarcelLee**
fix issue #76 ```fd2-up.linux.bash``` does not setup proper groups

**Pull Request Description**

Added bash commands in /bin/fd2-up.linux.bash to add necessary groups and grpid in WSL2 environment to start fd2

Closes #76

---

**Licensing Certification**

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request **I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)** for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
My initial run of `fd2-up.bash` showed the following error:
image

I was able to:
- connect via VNC
- open a terminal
- make changes to a file and save it
- install the sample database
- Open `http://farmos` in the browser and log in.
- `npm install` all dependencies
- build the FarmData2 module: `npm run build:fd2` and see it in farmOS

But when attempting to run the tests I encountered errors with:
- `test.bash --comp`
- `test.bash --unit --lib`
Tests that did not make API calls succeeded but those that made API calls failed. Many fail with status code 500.  Which suggests server configuration error.  

After a `fd2-down.bash` and `fd2-up.bash` I did not see the SQL Error above, however the issue with running tests and API calls persists.

I'll do some additional investigation to figure out what is causing this.

@JingyuMarcelLee ~~can you do the `npm install` and try the test commands on your install and report back?~~ See below...

**Comment by braughtg** [comment]
> I'll do some additional investigation to figure out what is causing this.

This seems to be an issue with the OAuth keys.

The following provided a manual fix:
- In Docker Desktop: 
  - Open a terminal on the `fd2_farmos` container
  - `cd /opt/drupal`
  - `chown www-data keys`
  - `chgrp www-data keys`
- In farmOS logged in as `admin`
  - Go to: Administration -> Configuration -> Web Services -> Consumers
  - Click the "Settings" button
  - Scroll down and click "Generate Keys"
  - Enter `../keys` for the "Directory for the Keys"
  - Click "Generate"

In the browser, clear recent history.

Try the test commands again:
- `test.bash --comp`
- `test.bash --unit --lib`

They should now run.

@JingyuMarcelLee Can you try the above and report back here?  Thanks!

If that works for you, then I will develop an automated process for generating the keys.

**Comment by braughtg** [comment]
I just created an issue in FarmData2/FD2-Images that describes a proposed fix:
 - https://github.com/FarmData2/FD2-Images/issues/3

**Comment by JingyuMarcelLee** [comment]
> > I'll do some additional investigation to figure out what is causing this.
> 
> This seems to be an issue with the OAuth keys.
> 
> The following provided a manual fix:
> 
> * In Docker Desktop:
>   
>   * Open a terminal on the `fd2_farmos` container
>   * `cd /opt/drupal`
>   * `chown www-data keys`
>   * `chgrp www-data keys`
> * In farmOS logged in as `admin`
>   
>   * Go to: Administration -> Configuration -> Web Services -> Consumers
>   * Click the "Settings" button
>   * Scroll down and click "Generate Keys"
>   * Enter `../keys` for the "Directory for the Keys"
>   * Click "Generate"
> 
> In the browser, clear recent history.
> 
> Try the test commands again:
> 
> * `test.bash --comp`
> * `test.bash --unit --lib`
> 
> They should now run.
> 
> @JingyuMarcelLee Can you try the above and report back here? Thanks!
> 
> If that works for you, then I will develop an automated process for generating the keys.

I tried running the cypress tests in both the dev container and host(WSL2). After following your instructions, both ```--comp``` and ```--unit --lib``` test passed without issues in the dev container. However, Cypress failed to verify (timeout after 30000 milisec) in the WSL2 environment and it seemed like some of the cypress configurations were not supported in WSL2. I think we will just have to run the cypress tests in the dev container (unless someone wants to add support for WSL2 for Cypress). I also had to manually install cypress inside the dev container using ```npx cypress install``` as ```npm install``` did not install it automatically.

**Comment by braughtg** [comment]
@JingyuMarcelLee I just migrated the development branch to farmOS v3.x.  That included producing a new farmOS docker image and sample database.  In doing so, I think I fixed the issues you were experiencing with getting the dev environment to launch from WSL (i.e. the farmos image now contains the ssl keys).

If you want to try this out:
- Update your development branch to the latest version.
- Merge that into your feature branch
- Delete all of the FarmData docker images and volumes in Docker Desktop
- Run `fd2-up.bash`
- In the dev container run `installDB.bash`
  - Pick release `2.0.1` - option 1 
  - Pick `db.sample.tar.gz` - option 2

With that done all of the tests should run in the dev environment.

Let me know here if this works for you and if so I'll test it here as well and then get this PR merged.

**Comment by braughtg** [comment]
@JingyuMarcelLee Did you close this on purpose?  The code you had for the Linux/WSL parts looked good.  Though I see they are no long here.

**Comment by braughtg** [comment]
@JingyuMarcelLee Ohhh, I think I see.  Looks like you had changed `development` and pushed those changes.  Be sure to work in a feature branch created from `development`.

**Comment by JingyuMarcelLee** [comment]
> @JingyuMarcelLee Ohhh, I think I see. Looks like you had changed `development` and pushed those changes. Be sure to work in a feature branch created from `development`.

Oops that was by mistake. I will reopen the request after I test the changes on the dev branch.

**Comment by JingyuMarcelLee** [comment]
Reopening PR with a different PR. Had to do this due to merge conflict happened after --force pulling. at #121

**Pull request closed without merging**
